### ISSUE TITLE
modify workflows for dependabots NOT using secrets

### ISSUE THREAD

**Issue by danieleTrimarchi** [Iconeus/chargedPlanner#27]
dependabot is not allowed to get secrets
So we should avoid getting the secrets when the user is dependabot 
and in this case, no tests should run on the LuccaAPI (which is the component requiring the secret) 

Exemple file : 
```yaml
name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests (skipped for Dependabot)
        if: github.actor != 'dependabot[bot]'
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: npm test

      - name: Lint code
        run: npm run lint
```
